name: Bug report
description: Report a problem with the AI Command Library
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include the exact commands you ran and any relevant context.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |-
        - OS version
        - Node.js version
        - CLI invocation (e.g. `npx link-ai-commands --provider claude`)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Drag and drop files or paste output.
