name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the library!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve? Why is it important?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Share any implementation ideas, commands, or pseudo-code.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
